version: 2

linters:
  disable-all: true
  enable:
    - govet
    - revive
    - gocyclo
    - errcheck
    - unconvert
    - ineffassign
    - unused
    - staticcheck

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - (io.Closer).Close

run:
  tests: true
  timeout: 5m
  skip-files:
    - ".*\\.gen\\.go$"
    - ".*_test\\.go$"

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes: github.com/my_org
  exclusions:
    paths:
      - ".*\\.gen\\.go$"
