version: "2"

linters:
  default: none
  enable:
    - govet
    - revive
    - gocyclo
    - errcheck
    - unconvert
    - ineffassign
    - unused
    - staticcheck

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - (io.Closer).Close
        - (net/http.ResponseWriter).Write

  exclusions:
    paths:
      - ".*\\.gen\\.go$"

run:
  tests: false
  timeout: 15m

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/mashiike
  exclusions:
    paths:
      - ".*\\.gen\\.go$"
